services:
  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    image: todo-backend
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

